object_base: orig/GMPE01_00
object: sys/main.dol
mw_comment_version: 10 # GC 2.6 linker

modules:
- object: files/dll/_minigameDll.rel
- object: files/dll/bootDll.rel
- object: files/dll/instDll.rel
- object: files/dll/m302Dll.rel
- object: files/dll/m303Dll.rel
- object: files/dll/m330Dll.rel
- object: files/dll/m333Dll.rel
- object: files/dll/m402Dll.rel
- object: files/dll/m403Dll.rel
- object: files/dll/m404Dll.rel
- object: files/dll/m405Dll.rel
- object: files/dll/m406Dll.rel
- object: files/dll/m407dll.rel
- object: files/dll/m408Dll.rel
- object: files/dll/m409Dll.rel
- object: files/dll/m410Dll.rel
- object: files/dll/m411Dll.rel
- object: files/dll/m412Dll.rel
- object: files/dll/m413Dll.rel
- object: files/dll/m414Dll.rel
- object: files/dll/m415Dll.rel
- object: files/dll/m416Dll.rel
- object: files/dll/m417Dll.rel
- object: files/dll/m418Dll.rel
- object: files/dll/m419Dll.rel
- object: files/dll/m420dll.rel
- object: files/dll/m421Dll.rel
- object: files/dll/m422Dll.rel
- object: files/dll/m423Dll.rel
- object: files/dll/m424Dll.rel
- object: files/dll/m425Dll.rel
- object: files/dll/m426Dll.rel
- object: files/dll/m427Dll.rel
- object: files/dll/m428Dll.rel
- object: files/dll/m429Dll.rel
- object: files/dll/m430Dll.rel
- object: files/dll/m431Dll.rel
- object: files/dll/m432Dll.rel
- object: files/dll/m433Dll.rel
- object: files/dll/m434Dll.rel
- object: files/dll/m435Dll.rel
- object: files/dll/m436Dll.rel
- object: files/dll/m437Dll.rel
- object: files/dll/m438Dll.rel
- object: files/dll/m439Dll.rel
- object: files/dll/m440Dll.rel
- object: files/dll/m441Dll.rel
- object: files/dll/m442Dll.rel
- object: files/dll/m443Dll.rel
- object: files/dll/m444dll.rel
- object: files/dll/m445Dll.rel
- object: files/dll/m446dll.rel
- object: files/dll/m447dll.rel
- object: files/dll/m448Dll.rel
- object: files/dll/m449Dll.rel
- object: files/dll/m450Dll.rel
- object: files/dll/m451Dll.rel
- object: files/dll/m453Dll.rel
- object: files/dll/m455Dll.rel
- object: files/dll/m456Dll.rel
- object: files/dll/m457Dll.rel
- object: files/dll/m458Dll.rel
- object: files/dll/m459dll.rel
- object: files/dll/m460Dll.rel
- object: files/dll/m461Dll.rel
- object: files/dll/m462Dll.rel
- object: files/dll/m463Dll.rel
- object: files/dll/mentDll.rel
- object: files/dll/messDll.rel
- object: files/dll/mgmodedll.rel
- object: files/dll/modeltestDll.rel
- object: files/dll/modeseldll.rel
- object: files/dll/mpexDll.rel
- object: files/dll/msetupDll.rel
- object: files/dll/mstory2Dll.rel
- object: files/dll/mstory3Dll.rel
- object: files/dll/mstory4Dll.rel
- object: files/dll/mstoryDll.rel
- object: files/dll/nisDll.rel
- object: files/dll/option.rel
- object: files/dll/present.rel
- object: files/dll/resultDll.rel
- object: files/dll/safDll.rel
- object: files/dll/selmenuDll.rel
- object: files/dll/staffDll.rel
- object: files/dll/subchrselDll.rel
- object: files/dll/w01Dll.rel
- object: files/dll/w02Dll.rel
- object: files/dll/w03Dll.rel
- object: files/dll/w04Dll.rel
- object: files/dll/w05Dll.rel
- object: files/dll/w06Dll.rel
- object: files/dll/w10Dll.rel
- object: files/dll/w20Dll.rel
- object: files/dll/w21Dll.rel
- object: files/dll/ztardll.rel
- object: files/dll/E3setupDLL.rel
  links: [_minigameDll]
- object: files/dll/m300Dll.rel
  links: [_minigameDll]
- object: files/dll/m401Dll.rel
  links: [_minigameDll]
